import Navbar from '@/components/Navbar'
import { ReduxProvider } from '@/redux/provider'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ThemeProvider } from "@/components/theme-provider"
import '../styles/globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'heyajaysingh',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <ReduxProvider>
            <div>
              <Navbar />
              {children}
            </div>
          </ReduxProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
